[server]
address = "0.0.0.0"
port = 8503
headless = true
# Leave defaults to avoid warnings; can override via CLI if needed

[theme]
primaryColor = "#2563EB"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0f172a"
font = "sans serif"


